/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface Course {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'creator' : Principal,
  'thumbnail' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'description' : string,
}
export interface CourseUpdate {
  'categoryId' : bigint,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'content' : [] | [ExternalBlob],
  'order' : bigint,
  'lessonType' : LessonType,
  'videoUrl' : string,
  'courseId' : bigint,
}
export type LessonType = { 'pdf' : null } |
  { 'video' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface LessonUpdate {
  'title' : string,
  'content' : [] | [ExternalBlob],
  'order' : bigint,
  'lessonType' : LessonType,
  'videoUrl' : string,
  'courseId' : bigint,
}
export interface Quiz { 'questions' : Array<QuizQuestion>, 'courseId' : bigint }
export interface QuizQuestion {
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface User {
  'username' : string,
  'dateOfBirth' : bigint,
  'createdAt' : bigint,
  'email' : string,
}
export interface UserProfile {
  'username' : string,
  'dateOfBirth' : bigint,
  'createdAt' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserUpdate {
  'username' : string,
  'dateOfBirth' : bigint,
  'email' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'askDoubt' : ActorMethod<[bigint, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createCourse' : ActorMethod<
    [string, string, bigint, [] | [ExternalBlob]],
    bigint
  >,
  'createLesson' : ActorMethod<[LessonUpdate], bigint>,
  'createQuiz' : ActorMethod<[bigint, Array<QuizQuestion>], undefined>,
  'createUser' : ActorMethod<[UserUpdate], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteLesson' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[bigint], Category>,
  'getCourse' : ActorMethod<[bigint], Course>,
  'getDoubtHistory' : ActorMethod<
    [bigint],
    [] | [
      {
        'question' : string,
        'answer' : string,
        'timestamp' : bigint,
        'courseId' : bigint,
      }
    ]
  >,
  'getLesson' : ActorMethod<[bigint], Lesson>,
  'getQuiz' : ActorMethod<[bigint], [] | [Quiz]>,
  'getUser' : ActorMethod<[Principal], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCoursesByTitle' : ActorMethod<[string], Array<Course>>,
  'updateCategory' : ActorMethod<[bigint, string], undefined>,
  'updateCourse' : ActorMethod<[bigint, CourseUpdate], undefined>,
  'updateLesson' : ActorMethod<[bigint, LessonUpdate], undefined>,
  'updateUser' : ActorMethod<[UserUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];