/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LessonType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const LessonUpdate = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Opt(ExternalBlob),
  'order' : IDL.Nat,
  'lessonType' : LessonType,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserUpdate = IDL.Record({
  'username' : IDL.Text,
  'dateOfBirth' : IDL.Int,
  'email' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const User = IDL.Record({
  'username' : IDL.Text,
  'dateOfBirth' : IDL.Int,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'dateOfBirth' : IDL.Int,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Opt(ExternalBlob),
  'order' : IDL.Nat,
  'lessonType' : LessonType,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const Quiz = IDL.Record({
  'questions' : IDL.Vec(QuizQuestion),
  'courseId' : IDL.Nat,
});
export const CourseUpdate = IDL.Record({
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'askDoubt' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createLesson' : IDL.Func([LessonUpdate], [IDL.Nat], []),
  'createQuiz' : IDL.Func([IDL.Nat, IDL.Vec(QuizQuestion)], [], []),
  'createUser' : IDL.Func([UserUpdate], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteLesson' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getDoubtHistory' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'question' : IDL.Text,
            'answer' : IDL.Text,
            'timestamp' : IDL.Int,
            'courseId' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getLesson' : IDL.Func([IDL.Nat], [Lesson], ['query']),
  'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(Quiz)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCoursesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, CourseUpdate], [], []),
  'updateLesson' : IDL.Func([IDL.Nat, LessonUpdate], [], []),
  'updateUser' : IDL.Func([UserUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LessonType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const LessonUpdate = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Opt(ExternalBlob),
    'order' : IDL.Nat,
    'lessonType' : LessonType,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserUpdate = IDL.Record({
    'username' : IDL.Text,
    'dateOfBirth' : IDL.Int,
    'email' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const User = IDL.Record({
    'username' : IDL.Text,
    'dateOfBirth' : IDL.Int,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'dateOfBirth' : IDL.Int,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Opt(ExternalBlob),
    'order' : IDL.Nat,
    'lessonType' : LessonType,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const Quiz = IDL.Record({
    'questions' : IDL.Vec(QuizQuestion),
    'courseId' : IDL.Nat,
  });
  const CourseUpdate = IDL.Record({
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'askDoubt' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createLesson' : IDL.Func([LessonUpdate], [IDL.Nat], []),
    'createQuiz' : IDL.Func([IDL.Nat, IDL.Vec(QuizQuestion)], [], []),
    'createUser' : IDL.Func([UserUpdate], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteLesson' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getDoubtHistory' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'question' : IDL.Text,
              'answer' : IDL.Text,
              'timestamp' : IDL.Int,
              'courseId' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getLesson' : IDL.Func([IDL.Nat], [Lesson], ['query']),
    'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(Quiz)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCoursesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, CourseUpdate], [], []),
    'updateLesson' : IDL.Func([IDL.Nat, LessonUpdate], [], []),
    'updateUser' : IDL.Func([UserUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };