/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}
export type Time = bigint;
export interface User {
    username: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    email: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    question: string;
    correctIndex: bigint;
    options: Array<string>;
}
export interface Quiz {
    questions: Array<QuizQuestion>;
    courseId: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LessonUpdate {
    title: string;
    content?: ExternalBlob;
    order: bigint;
    lessonType: LessonType;
    videoUrl: string;
    courseId: bigint;
}
export interface Course {
    id: bigint;
    categoryId: bigint;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    createdAt: bigint;
    description: string;
}
export interface CommunityPostView {
    id: bigint;
    title: string;
    likeCount: bigint;
    body: string;
    createdAt: Time;
    likes: Array<Principal>;
    authorPrincipal: Principal;
}
export interface CommunityComment {
    id: bigint;
    body: string;
    createdAt: Time;
    authorPrincipal: Principal;
    postId: bigint;
}
export interface Lesson {
    id: bigint;
    title: string;
    content?: ExternalBlob;
    order: bigint;
    lessonType: LessonType;
    videoUrl: string;
    courseId: bigint;
}
export interface CourseUpdate {
    categoryId: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    description: string;
}
export interface UserUpdate {
    username: string;
    dateOfBirth: bigint;
    email: string;
}
export interface UserProfile {
    username: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum LessonType {
    pdf = "pdf",
    video = "video",
    text = "text",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    askDoubt(courseId: bigint, question: string): Promise<string>;
    askGeneralDoubt(question: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(name: string): Promise<void>;
    createComment(postId: bigint, body: string): Promise<bigint>;
    createCourse(title: string, description: string, categoryId: bigint, thumbnail: ExternalBlob | null): Promise<bigint>;
    createLesson(update: LessonUpdate): Promise<bigint>;
    createPost(title: string, body: string): Promise<bigint>;
    createQuiz(courseId: bigint, questions: Array<QuizQuestion>): Promise<void>;
    createUser(userRequest: UserUpdate): Promise<void>;
    deleteCategory(categoryId: bigint): Promise<void>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteCourse(courseId: bigint): Promise<void>;
    deleteLesson(lessonId: bigint): Promise<void>;
    deletePost(id: bigint): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    getAllCategories(): Promise<Array<Category>>;
    getAllCourses(): Promise<Array<Course>>;
    getAllPosts(): Promise<Array<CommunityPostView>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategory(categoryId: bigint): Promise<Category>;
    getCommentsForPost(postId: bigint): Promise<Array<CommunityComment>>;
    getCourse(courseId: bigint): Promise<Course>;
    getDoubtHistory(courseId: bigint): Promise<{
        question: string;
        answer: string;
        timestamp: bigint;
        courseId: bigint;
    } | null>;
    getLesson(lessonId: bigint): Promise<Lesson>;
    getLessonsForCourse(courseId: bigint): Promise<Array<Lesson>>;
    getPost(id: bigint): Promise<CommunityPostView | null>;
    getQuiz(courseId: bigint): Promise<Quiz | null>;
    getUser(user: Principal): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserLiked(postId: bigint, user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCoursesByTitle(searchTerm: string): Promise<Array<Course>>;
    unlikePost(postId: bigint): Promise<void>;
    updateCategory(categoryId: bigint, name: string): Promise<void>;
    updateCourse(courseId: bigint, update: CourseUpdate): Promise<void>;
    updateLesson(lessonId: bigint, update: LessonUpdate): Promise<void>;
    updateUser(user: UserUpdate): Promise<void>;
}
import type { CommunityPostView as _CommunityPostView, Course as _Course, CourseUpdate as _CourseUpdate, ExternalBlob as _ExternalBlob, Lesson as _Lesson, LessonType as _LessonType, LessonUpdate as _LessonUpdate, Quiz as _Quiz, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async askDoubt(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askDoubt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askDoubt(arg0, arg1);
            return result;
        }
    }
    async askGeneralDoubt(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askGeneralDoubt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askGeneralDoubt(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1);
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createLesson(arg0: LessonUpdate): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(await to_candid_LessonUpdate_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(await to_candid_LessonUpdate_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPost(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async createQuiz(arg0: bigint, arg1: Array<QuizQuestion>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1);
            return result;
        }
    }
    async createUser(arg0: UserUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<CommunityPostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: bigint): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return result;
        }
    }
    async getCommentsForPost(arg0: bigint): Promise<Array<CommunityComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPost(arg0);
            return result;
        }
    }
    async getCourse(arg0: bigint): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_Course_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_Course_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtHistory(arg0: bigint): Promise<{
        question: string;
        answer: string;
        timestamp: bigint;
        courseId: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtHistory(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtHistory(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: bigint): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_Lesson_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_Lesson_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonsForCourse(arg0: bigint): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getLessonsForCourse(arg0);
                return await Promise.all(result.map((x: any) => from_candid_Lesson_n25(this._uploadFile, this._downloadFile, x)));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getLessonsForCourse(arg0);
            return await Promise.all(result.map((x: any) => from_candid_Lesson_n25(this._uploadFile, this._downloadFile, x)));
        }
    }
    async getPost(arg0: bigint): Promise<CommunityPostView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: bigint): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserLiked(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLiked(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLiked(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCoursesByTitle(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCoursesByTitle(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCoursesByTitle(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateCourse(arg0: bigint, arg1: CourseUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, await to_candid_CourseUpdate_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, await to_candid_CourseUpdate_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLesson(arg0: bigint, arg1: LessonUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, await to_candid_LessonUpdate_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, await to_candid_LessonUpdate_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUser(arg0: UserUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0);
            return result;
        }
    }
}
async function from_candid_Course_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Promise<Course> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LessonType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonType): LessonType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Lesson_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Promise<Lesson> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        question: string;
        answer: string;
        timestamp: bigint;
        courseId: bigint;
    }]): {
    question: string;
    answer: string;
    timestamp: bigint;
    courseId: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommunityPostView]): CommunityPostView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    title: string;
    creator: Principal;
    thumbnail: [] | [_ExternalBlob];
    createdAt: bigint;
    description: string;
}): Promise<{
    id: bigint;
    categoryId: bigint;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    createdAt: bigint;
    description: string;
}> {
    return {
        id: value.id,
        categoryId: value.categoryId,
        title: value.title,
        creator: value.creator,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.thumbnail)),
        createdAt: value.createdAt,
        description: value.description
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: [] | [_ExternalBlob];
    order: bigint;
    lessonType: _LessonType;
    videoUrl: string;
    courseId: bigint;
}): Promise<{
    id: bigint;
    title: string;
    content?: ExternalBlob;
    order: bigint;
    lessonType: LessonType;
    videoUrl: string;
    courseId: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        content: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.content)),
        order: value.order,
        lessonType: from_candid_LessonType_n27(_uploadFile, _downloadFile, value.lessonType),
        videoUrl: value.videoUrl,
        courseId: value.courseId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    video: null;
} | {
    text: null;
} | {
    image: null;
}): LessonType {
    return "pdf" in value ? LessonType.pdf : "video" in value ? LessonType.video : "text" in value ? LessonType.text : "image" in value ? LessonType.image : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Promise<Array<Course>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Course_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_CourseUpdate_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseUpdate): Promise<_CourseUpdate> {
    return await to_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LessonType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): _LessonType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_LessonUpdate_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonUpdate): Promise<_LessonUpdate> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content?: ExternalBlob;
    order: bigint;
    lessonType: LessonType;
    videoUrl: string;
    courseId: bigint;
}): Promise<{
    title: string;
    content: [] | [_ExternalBlob];
    order: bigint;
    lessonType: _LessonType;
    videoUrl: string;
    courseId: bigint;
}> {
    return {
        title: value.title,
        content: value.content ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.content)) : candid_none(),
        order: value.order,
        lessonType: to_candid_LessonType_n14(_uploadFile, _downloadFile, value.lessonType),
        videoUrl: value.videoUrl,
        courseId: value.courseId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    description: string;
}): Promise<{
    categoryId: bigint;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    description: string;
}> {
    return {
        categoryId: value.categoryId,
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        description: value.description
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): {
    pdf: null;
} | {
    video: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == LessonType.pdf ? {
        pdf: null
    } : value == LessonType.video ? {
        video: null
    } : value == LessonType.text ? {
        text: null
    } : value == LessonType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
